
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ml_project"
version = "0.1.0"
description = "Production-ready ML project"
requires-python = ">=3.9"

dependencies = [
    "pandas",
    "scikit-learn",
    "numpy"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]